server:
  port: 8083

spring.cloud.stream:
  function:
    definition: supplier;consumer
  bindings:
    supplier-out-0:
      destination: order-created
    consumer-in-0:
      destination: order-updated





#spring.cloud.stream:
#  function:
#    definition: supplier;consumer
#  bindings:
#    supplier-out-0:
#      destination: order-created
#    consumer-in-0:
#      destination: order-updated
---
spring:
  jpa:
    defer-datasource-initialization: true



#  kafka:
#    #    producer:
#    #      binder:
#    #        brokers: pkc-56d1g.eastus.azure.confluent.cloud:9092
#    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#    #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.acme.*