server:
  port: 8084
---

spring.cloud.stream:
  function:
    definition: processor
  bindings:
    processor-in-0:
      destination: order-created
    processor-out-0:
      destination: order-updated
  kafka:
    binder:
      replication-factor: 1


#spring:
#  kafka:
#    consumer:
#      bootstrap-servers: pkc-56d1g.eastus.azure.confluent.cloud:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.acme.dto
---
service:
  endpoints:
    inventory: http://localhost:8081
    payment: http://localhost:8082