server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: chirag
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

inventory:
  datasource:
    host: localhost
    port: 5432
    database: inventory
    username: postgres
    password: chirag

